[package]
name = "colliculus"
version = "0.1.0"
authors = ["John Else <john.else@gmail.com>"]

[dependencies]
vst = "0.0.1"

vstutils = {version = "0.1.0", path = "../../lib/vstutils"}

[lib]
crate-type = ["cdylib"]
