[package]
name = "monosine"
version = "0.1.0"
authors = ["John Else <john.else@gmail.com>"]

[dependencies]
vst = "0.0.1"

generator = {version = "0.1.0", path = "../../lib/generator"}

[lib]
crate-type = ["cdylib"]
